//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_access
    {
        public int access_id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> hasAccess { get; set; }
    }
}
