//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_product_release
    {
        public int transactionlog_id { get; set; }
        public Nullable<int> sales_detail_id { get; set; }
        public Nullable<int> sales_id { get; set; }
        public Nullable<int> releaseQTY { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
    }
}
