//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_productDetail
    {
        public int product_detail_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string measurement { get; set; }
        public Nullable<double> measurevalue { get; set; }
        public Nullable<double> supplierprice { get; set; }
        public Nullable<double> retailprice { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> isDelete { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
